### ISSUE TITLE
Something might be broken?

### ISSUE THREAD

**Issue by rcon420** [Natanel-Shitrit/Chat-Tick-Muter#1]
I don't have any errors but the plugin seems to not work I still hear ticking sound

**Comment by Natanel-Shitrit** [comment]
This is probably due other plugin modifying the messages.
The most obvious plugins would be chat processors.
If you can't find the plugin that causes it i can help you with that just add a list of the plugins (`sm plugins list`)

**Comment by rcon420** [comment]
> This is probably due other plugin modifying the messages.
> The most obvious plugins would be chat processors.
> If you can't find the plugin that causes it i can help you with that just add a list of the plugins (`sm plugins list`)

Oh yes the only plugin that modifies messages for me is Chat-Proccesor and one of my VIP plugins give chat color with chat proccesor
